// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Waitlisted struct {
	ID              uuid.UUID
	TwitterID       string
	TwitterUsername string
	Referrer        sql.NullString
	Email           string
	WalletAddress   string
}
